### ISSUE TITLE
NoteProxy typo

### ISSUE THREAD

**Issue by paum3** [BZoennchen/supercollider-book#1]
Hi Benedikt, your book is a marvelous compendium, well-written, and I am all in for the philosophy interconnections. While reading, I found a typo: `NoteProxy` should be `NodeProxy`, at least on this page: https://bzoennchen.github.io/supercollider-book/chapters/supercollider/live-coding/2-proxy-space.html.

Thank you.

**Comment by BZoennchen** [comment]
Hi Fero, 

thank you very much. I updated the typo :). I am working on the book for some time and there is still a lot to do. I am still not ready to post it in the official SC Forum but I plan to do so very soon. Sadly, I have not that much time to work on it.

Thank you very much for your kind words.

**Comment by paum3** [comment]
Benedikt, I'm happy to help. I've checked your CT book, and it's great, too. Do you plan to translate it into English? I know it's probably not likely, given that it's time-consuming, but it doesn't hurt to ask.)

**Comment by BZoennchen** [comment]
I corrected the typo.
