### ISSUE TITLE
Unclear sentence in /chapters/preamble/heidegger.html

### ISSUE THREAD

**Issue by acli** [BZoennchen/supercollider-book#9]
In the paragraph

>I find Haneke’s project important. However, if such an unconcealment of the hyper-real is possible, or if even the most unpleasant depiction of violence in reference to the medium itself—e.g. by breaking the fourth wall—will lead to the same old effect, that is, more violence is questionable.

the second sentence has no main verb so the meaning is unclear. (The whole sentence, as it stands, is a very long “if” clause.) Perhaps the “that is,” should be a “then”, or perhaps the conclusion has been deleted by mistake.

**Comment by BZoennchen** [comment]
I changed it to:

> I find Haneke's project important.
> However, it is questionable whether such an unconcealment of the *hyper-real* is possible, or if even the most unpleasant depiction of violence, in reference to the medium itself---for example, by breaking the fourth wall---will merely lead to the same old effect: more violence.

Is it now clear :=)?

**Comment by acli** [comment]
Yes, it’s good :-)
